import asyncio
from datetime import date
from math import ceil
from uuid import UUID

from sqlalchemy import delete, or_, select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.core.config import settings
from app.core.security import hash_password
from app.models import (
    Book,
    Classroom,
    ScoreRecord,
    Student,
    StudentBookScore,
    Teacher,
    Work,
    WorkHistory,
)
from app.services.score_service import add_score
from app.services.work_service import create_or_replace_work

DEMO_TAG = "[demo]"
DEMO_SCHOOL = f"Demo Academy {DEMO_TAG}"
DEMO_ADDRESS = f"Generated by seed script {DEMO_TAG}"
DEMO_STUDENT_PHONE_PREFIX = "1379000"
TERMS = ["spring", "summer", "autumn"]

DEMO_TEACHERS = [
    {"name": "Demo Admin", "phone": "13990000001", "role": "admin", "password": "admin123"},
    {"name": "Demo Teacher A", "phone": "13990000002", "role": "teacher", "password": "123456"},
    {"name": "Demo Teacher B", "phone": "13990000003", "role": "teacher", "password": "123456"},
    {"name": "Demo Teacher C", "phone": "13990000004", "role": "teacher", "password": "123456"},
]

DEMO_CLASSROOMS = [
    ("Demo Class 1A", "1"),
    ("Demo Class 1B", "1"),
    ("Demo Class 2A", "2"),
    ("Demo Class 3A", "3"),
    ("Demo Class 4A", "4"),
    ("Demo Class 5A", "5"),
]

DEMO_BOOKS = [
    ("Demo Book 01", 1),
    ("Demo Book 02", 2),
    ("Demo Book 03", 3),
    ("Demo Book 04", 4),
    ("Demo Book 05", 5),
    ("Demo Book 06", 6),
    ("Demo Book 07", 7),
    ("Demo Book 08", 8),
    ("Demo Book 09", 9),
    ("Demo Book 10", 10),
    ("Demo Book 11", 11),
    ("Demo Book 12", 12),
]

PROFILE_TARGETS = [300, 1700, 3300, 5200]


def _demo_student_phone(index: int) -> str:
    return f"{DEMO_STUDENT_PHONE_PREFIX}{index:04d}"


def _uuid(value: str) -> UUID:
    return UUID(value)


async def _current_total(student_id: str, db: AsyncSession) -> int:
    row = await db.execute(select(Student.total_score).where(Student.id == _uuid(student_id)))
    return int(row.scalar_one())


async def clear_demo_data(db: AsyncSession) -> None:
    teacher_ids = [
        row[0]
        for row in (
            await db.execute(
                select(Teacher.id).where(Teacher.phone.in_([item["phone"] for item in DEMO_TEACHERS]))
            )
        ).all()
    ]
    classroom_ids = [
        row[0]
        for row in (
            await db.execute(select(Classroom.id).where(Classroom.description.like(f"%{DEMO_TAG}%")))
        ).all()
    ]
    student_ids = [
        row[0]
        for row in (
            await db.execute(
                select(Student.id).where(
                    Student.phone.like(f"{DEMO_STUDENT_PHONE_PREFIX}%"),
                    Student.school == DEMO_SCHOOL,
                )
            )
        ).all()
    ]
    book_ids = [
        row[0]
        for row in (
            await db.execute(select(Book.id).where(Book.description.like(f"%{DEMO_TAG}%")))
        ).all()
    ]
    work_ids = [
        row[0]
        for row in (
            await db.execute(
                select(Work.id).where(
                    or_(Work.student_id.in_(student_ids), Work.teacher_id.in_(teacher_ids))
                )
            )
        ).all()
    ]

    if work_ids:
        await db.execute(delete(WorkHistory).where(WorkHistory.work_id.in_(work_ids)))
    if student_ids:
        await db.execute(delete(ScoreRecord).where(ScoreRecord.student_id.in_(student_ids)))
        await db.execute(delete(StudentBookScore).where(StudentBookScore.student_id.in_(student_ids)))
        await db.execute(delete(Work).where(Work.student_id.in_(student_ids)))
        await db.execute(delete(Student).where(Student.id.in_(student_ids)))
    if classroom_ids:
        await db.execute(delete(Classroom).where(Classroom.id.in_(classroom_ids)))
    if book_ids:
        await db.execute(delete(Book).where(Book.id.in_(book_ids)))
    if teacher_ids:
        await db.execute(delete(Teacher).where(Teacher.id.in_(teacher_ids)))
    await db.commit()


async def _seed_student_progress(
    student: Student,
    teacher: Teacher,
    books: list[Book],
    profile_index: int,
    student_index: int,
    db: AsyncSession,
) -> None:
    term = TERMS[student_index % len(TERMS)]
    base_practice_books = [0, 2, 4, 6][profile_index]

    for book_index in range(base_practice_books):
        practice_score = 20 if profile_index == 1 else 50 if profile_index == 2 else 70
        await add_score(
            student_id=str(student.id),
            teacher_id=str(teacher.id),
            score_type="practice",
            score=practice_score,
            reason=f"demo-practice-{book_index + 1}",
            db=db,
            term=term,
            target_part="root",
            book_id=str(books[book_index].id),
        )
        if profile_index >= 2:
            await add_score(
                student_id=str(student.id),
                teacher_id=str(teacher.id),
                score_type="practice",
                score=practice_score,
                reason=f"demo-practice-{book_index + 1}-trunk",
                db=db,
                term=term,
                target_part="trunk",
                book_id=str(books[book_index].id),
            )

    homework_count = [1, 3, 5, 6][profile_index]
    for homework_index in range(homework_count):
        await add_score(
            student_id=str(student.id),
            teacher_id=str(teacher.id),
            score_type="homework",
            score=20 + profile_index * 10 + homework_index,
            reason=f"demo-homework-{homework_index + 1}",
            db=db,
            term=term,
        )

    competition_count = [1, 2, 4, 6][profile_index]
    for competition_index in range(competition_count):
        await add_score(
            student_id=str(student.id),
            teacher_id=str(teacher.id),
            score_type="competition",
            score=min(100, 40 + profile_index * 15 + competition_index * 5),
            reason=f"demo-competition-{competition_index + 1}",
            db=db,
            term=term,
        )

    if student_index < 12:
        await create_or_replace_work(
            student_id=str(student.id),
            teacher_id=str(teacher.id),
            data={
                "term": term,
                "slot_index": 1,
                "gallery_scope": "classroom" if student_index % 3 else "both",
                "image_url": f"/uploads/demo-work-{student_index + 1}-slot1.jpg",
                "description": f"Demo work slot 1 for student {student_index + 1}",
                "score": 70 + profile_index * 6,
            },
            db=db,
        )
    if student_index < 8:
        await create_or_replace_work(
            student_id=str(student.id),
            teacher_id=str(teacher.id),
            data={
                "term": term,
                "slot_index": 2,
                "gallery_scope": "school" if student_index % 2 == 0 else "both",
                "image_url": f"/uploads/demo-work-{student_index + 1}-slot2.jpg",
                "description": f"Demo work slot 2 for student {student_index + 1}",
                "score": 78 + profile_index * 5,
            },
            db=db,
        )

    target_total = PROFILE_TARGETS[profile_index] + (student_index // len(PROFILE_TARGETS)) * 75
    current_total = await _current_total(str(student.id), db)
    for bonus_index in range(ceil(max(target_total - current_total, 0) / 100)):
        remaining = target_total - await _current_total(str(student.id), db)
        if remaining <= 0:
            break
        await add_score(
            student_id=str(student.id),
            teacher_id=str(teacher.id),
            score_type="competition",
            score=min(100, remaining),
            reason=f"demo-bonus-{bonus_index + 1}",
            db=db,
            term=term,
        )


async def seed_demo_data(db: AsyncSession) -> None:
    await clear_demo_data(db)

    teachers: list[Teacher] = []
    for teacher_data in DEMO_TEACHERS:
        teacher = Teacher(
            name=teacher_data["name"],
            phone=teacher_data["phone"],
            password_hash=hash_password(teacher_data["password"]),
            role=teacher_data["role"],
        )
        db.add(teacher)
        teachers.append(teacher)
    await db.flush()
    teacher_pool = [teacher for teacher in teachers if teacher.role == "teacher"]

    classrooms: list[Classroom] = []
    for index, (name, grade_year) in enumerate(DEMO_CLASSROOMS):
        classroom = Classroom(
            name=name,
            grade_year=grade_year,
            description=f"{name} {DEMO_TAG}",
            teacher_id=teacher_pool[index % len(teacher_pool)].id,
        )
        db.add(classroom)
        classrooms.append(classroom)
    await db.flush()

    books: list[Book] = []
    for name, order_num in DEMO_BOOKS:
        book = Book(name=name, order_num=order_num, description=f"{name} {DEMO_TAG}")
        db.add(book)
        books.append(book)
    await db.flush()

    students: list[Student] = []
    total_students = 20
    for index in range(total_students):
        classroom = classrooms[index % len(classrooms)] if index < total_students - 2 else None
        grade = classroom.grade_year if classroom else str((index % 5) + 1)
        student = Student(
            name=f"Demo Student {index + 1:02d}",
            phone=_demo_student_phone(index + 1),
            password_hash=hash_password("111111"),
            grade=grade,
            gender="male" if index % 2 == 0 else "female",
            birthday=date(2013 + (index % 5), (index % 12) + 1, (index % 20) + 1),
            school=DEMO_SCHOOL,
            address=DEMO_ADDRESS,
            classroom_id=classroom.id if classroom else None,
            created_by=teacher_pool[index % len(teacher_pool)].id,
        )
        db.add(student)
        students.append(student)
    await db.commit()

    for index, student in enumerate(students):
        teacher = teacher_pool[index % len(teacher_pool)]
        await _seed_student_progress(
            student=student,
            teacher=teacher,
            books=books,
            profile_index=index % len(PROFILE_TARGETS),
            student_index=index,
            db=db,
        )


async def main() -> None:
    engine = create_async_engine(settings.DATABASE_URL, echo=True)
    session_factory = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    async with session_factory() as db:
        await seed_demo_data(db)
    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())
